import '../models/game_theme.dart';

const List<GameTheme> themes = [
  GameTheme(id: '1', title: '気持ちいいもの'),
  GameTheme(id: '2', title: '恥ずかしいシチュエーション'),
  GameTheme(id: '3', title: '興奮すること'),
  GameTheme(id: '4', title: '大人のおもちゃ'),
  GameTheme(id: '5', title: 'ベッドでの行為'),
  GameTheme(id: '6', title: 'キスしたい場所'),
  GameTheme(id: '7', title: '夜の営み'),
  GameTheme(id: '8', title: 'セクシーな仕草'),
  GameTheme(id: '9', title: '禁断の関係'),
  GameTheme(id: '10', title: 'ドキドキする瞬間'),
  GameTheme(id: '11', title: '誘惑の方法'),
  GameTheme(id: '12', title: '甘い言葉'),
  GameTheme(id: '13', title: '秘密の場所'),
  GameTheme(id: '14', title: '大人の遊び'),
  GameTheme(id: '15', title: 'ムラムラすること'),
  GameTheme(id: '16', title: '恋人にしてほしいこと'),
  GameTheme(id: '17', title: 'いけない妄想'),
  GameTheme(id: '18', title: 'セクシーな服装'),
  GameTheme(id: '19', title: '夜のデート'),
  GameTheme(id: '20', title: '愛の言葉'),
  GameTheme(id: '21', title: 'エッチなシチュエーション'),
  GameTheme(id: '22', title: '密かな願望'),
  GameTheme(id: '23', title: 'ときめく行動'),
  GameTheme(id: '24', title: '大人の秘密'),
  GameTheme(id: '25', title: 'イチャイチャすること'),
  GameTheme(id: '26', title: '燃える展開'),
  GameTheme(id: '27', title: 'ロマンチックな場面'),
  GameTheme(id: '28', title: '誘惑されるシーン'),
  GameTheme(id: '29', title: '官能的なもの'),
  GameTheme(id: '30', title: '二人きりの時間'),
];
