import '../models/game_theme.dart';

const List<GameTheme> themes = [
  GameTheme(id: '1', titleKey: 'theme1'),
  GameTheme(id: '2', titleKey: 'theme2'),
  GameTheme(id: '3', titleKey: 'theme3'),
  GameTheme(id: '4', titleKey: 'theme4'),
  GameTheme(id: '5', titleKey: 'theme5'),
  GameTheme(id: '6', titleKey: 'theme6'),
  GameTheme(id: '7', titleKey: 'theme7'),
  GameTheme(id: '8', titleKey: 'theme8'),
  GameTheme(id: '9', titleKey: 'theme9'),
  GameTheme(id: '10', titleKey: 'theme10'),
  GameTheme(id: '11', titleKey: 'theme11'),
  GameTheme(id: '12', titleKey: 'theme12'),
  GameTheme(id: '13', titleKey: 'theme13'),
  GameTheme(id: '14', titleKey: 'theme14'),
  GameTheme(id: '15', titleKey: 'theme15'),
  GameTheme(id: '16', titleKey: 'theme16'),
  GameTheme(id: '17', titleKey: 'theme17'),
  GameTheme(id: '18', titleKey: 'theme18'),
  GameTheme(id: '19', titleKey: 'theme19'),
  GameTheme(id: '20', titleKey: 'theme20'),
  GameTheme(id: '21', titleKey: 'theme21'),
  GameTheme(id: '22', titleKey: 'theme22'),
  GameTheme(id: '23', titleKey: 'theme23'),
  GameTheme(id: '24', titleKey: 'theme24'),
  GameTheme(id: '25', titleKey: 'theme25'),
  GameTheme(id: '26', titleKey: 'theme26'),
  GameTheme(id: '27', titleKey: 'theme27'),
  GameTheme(id: '28', titleKey: 'theme28'),
  GameTheme(id: '29', titleKey: 'theme29'),
  GameTheme(id: '30', titleKey: 'theme30'),
];
